[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
  NETLIFY_USE_BUN = "false"
  NETLIFY_USE_PNPM = "true"
  PNPM_VERSION = "8.15.4"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://random.imagecdn.app/.*"]

# 修复异常链接：/xxx/index.txt -> /xxx （保留查询串）
[[redirects]]
  from = "/:splat/index.txt"
  to = "/:splat"
  status = 301
  force = true
